### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by sigkell** [UCC2021/ucc2021.github.io#2]
Website lacks a favicon (the icon displayed in the browser tab/window).

**Comment by HaplessQuark** [comment]
I dont really know how this works  but I'm pretty sure this
<link rel="shortcut icon" href="http://www.ucc.ie/favicon.ico">
should add the ucc crest favicon. I don't know how to implement that though

**Comment by sigkell** [comment]
Looks like it should work, it mightn't though if UCC's site has a CORS policy (prevents other websites from using things coming from their domain).

Github uses Markdown, to stick code in you can either indent it by four spaces (which'll give you this)

    <link rel="shortcut icon" href="http://www.ucc.ie/favicon.ico">

...or surround your code with three backticks and specify a language, which'll give you this:

```html
<link rel="shortcut icon" href="http://www.ucc.ie/favicon.ico">
```

I'll assign you to this issue though, hopefully after tomorrow people can start trying some things with the site :)
